FROM praekeltfoundation/alpine-buildpack-deps:3.8-scm

RUN apk add --no-cache \
        autoconf \
        automake \
        bzip2 \
        bzip2-dev \
        curl-dev \
        db-dev \
        dpkg \
        dpkg-dev \
        file \
        g++ \
        gcc \
        gdbm-dev \
        geoip-dev \
        glib-dev \
        imagemagick-dev \
        jpeg-dev \
        krb5-dev \
        libc-dev \
        libevent-dev \
        libffi-dev \
        libpng-dev \
        libressl-dev \
        libtool \
        libwebp-dev \
        libxml2-dev \
        libxslt-dev \
        linux-headers \
        make \
        mariadb-dev \
        ncurses-dev \
        patch \
        postgresql-dev \
        readline-dev \
        sqlite-dev \
        xz \
        xz-dev \
        yaml-dev \
        zlib-dev
